#!/usr/bin/env bash

# DOTFILES=".dotfiles"
DOT=".dotfiles"
DOTFILES="${DOTFILES:-$HOME/$DOT}"
GIT_REPO="craveytrain/dotfiles"

# Symlink all the things!
declare -A symlinks
symlinks["bash/bash_profile"]=
symlinks["bash/bashrc"]=
symlinks["dev/editorconfig"]=
symlinks["dev/eslintrc.yaml"]=
symlinks["dev/stylelintrc.yaml"]=
symlinks["git/gitconfig"]=
symlinks["git/gitignore_global"]=
symlinks["vim/vimrc"]=".vim/vimrc"
symlinks["vim/spell/en.utf-8.add"]=".vim/spell/en.utf-8.add"
symlinks["zsh/zlogin.zsh"]=".zlogin"
symlinks["zsh/zprofile.zsh"]=".zprofile"
symlinks["zsh/zshenv.zsh"]=".zshenv"
symlinks["zsh/zshrc.zsh"]=".zshrc"

# Grab dotfiles if they aren't already installed
if [ ! -d "$DOTFILES" ]; then
  # Prefer git clone
  if hash git 2>/dev/null; then
    # Clone git repo if not already there
    git clone --recursive "git://github.com/$GIT_REPO.git" "$DOT"
  else
    # If curl not found, give up
    hash curl 2>/dev/null || { echo >&2 "Curl not found, giving up."; exit 1; }

    echo "Git not found. Copying instead."
    mkdir "$DOTFILES";
    curl -L "https://github.com/$GIT_REPO/tarball/master" | tar zx -C "$DOT" --strip-components 1
  fi
fi

for src in "${!symlinks[@]}"; do
  NEW_FILE="$HOME/${symlinks[$src]:-.$(basename $src)}"
  NEW_FILE_DIR="$(dirname $NEW_FILE)"

  # If the file already exists (just not a symlink), back it up
  if [ -e "$NEW_FILE" ] && [ ! -L "$NEW_FILE" ]; then
    BASE="$(basename $NEW_FILE)"
    echo "Backup: $BASE -> ${BASE#.}.backup"
    mv "$NEW_FILE" "$NEW_FILE_DIR/${BASE#.}.backup"
  fi

  # If the diretory for the file does't not exist, create it
  if [ ! -d $NEW_FILE_DIR ]; then
    mkdir -p $NEW_FILE_DIR
  fi

  # if directory, remove it so it will be created again
  if [ -d "$NEW_FILE" ]; then
    rm "$NEW_FILE"
  fi

  # Symlink the file, replacing the old one
  ln -fs "$DOTFILES/$src" "$NEW_FILE"
done

echo "Please restart your shell"

exit 0;
