#!/usr/bin/env bash

# .bashrc

# set lang
export LANG=en_US.UTF-8

# shortcut to this dotfiles path is $DOTFILES
DOTFILES="$(cd "$(dirname "$(readlink ~/.bashrc)")" && cd .. && pwd)"
export DOTFILES

# keeping the paths simple
export PATH=$HOME/bin:$DOTFILES/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/coreutils:$PATH

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

source_if_present() {
  if [ -f "$1" ]; then
    # shellcheck source=$1
    . "$1"
  fi
}

source_files_by_name() {
  find "$DOTFILES" -name "$1" | while read source_file; do
    source_if_present "$source_file"
  done
}

# Source global definitions
source_if_present /etc/bashrc

# Makeup for lack of zprezto
source_if_present "$DOTFILES/bash/prompt.bash"
source_if_present "$DOTFILES/bash/aliases.bash"
source_if_present "$DOTFILES/bash/unarchive.sh"

# Load all the shared files
source_if_present "$DOTFILES/system/load.sh"

# Load completion scripts

source_if_present "$(brew --prefix)/etc/bash_completion"
